server:
  port: 8081

spring:
  data:
    mongodb:
      authentication-database: admin
      username: local
      password: local
      database: alert
      port: 27017
      host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/